### ISSUE TITLE
1.0.1 requires flumelog.close() method

### ISSUE THREAD

**Issue by christianbundy** [flumedb/test-flumelog#1]
It looks like there was a backward-incompatibility introduced in test-flumelog@1.0.1 where it now depends on a `flumelog.close()` method. Is `flumelog.close()` being added as a required method?

cc: @dominictarr

**Comment by dominictarr** [comment]
ah yeah, I guess that should have been a breaking change... on the other hand, it should have been a part of 1.0.0 in any case, lets add close to the flumelogs.
